"""Deterministic GRAPH_REPORT.md from a CodeGraph (no LLM)."""

from __future__ import annotations

import os
from collections import Counter, defaultdict

from codegraph.core.graph import CodeGraph
from codegraph.core.node import BaseNode, Edge
from codegraph.output.edge_provenance import edge_provenance


def _language_summary_from_nodes(nodes: list[BaseNode]) -> dict[str, int]:
    c: Counter[str] = Counter()
    for n in nodes:
        c[n.language.value.lower()] += 1
    return dict(sorted(c.items(), key=lambda x: (-x[1], x[0])))


def generate_graph_report_markdown(graph: CodeGraph) -> str:
    nodes = graph.nodes
    by_id: dict[str, BaseNode] = {n.id: n for n in nodes}
    out_deg: dict[str, int] = defaultdict(int)
    in_deg: dict[str, int] = defaultdict(int)
    edge_records: list[tuple[BaseNode, Edge]] = []

    for n in nodes:
        for e in n.edges:
            out_deg[n.id] += 1
            in_deg[e.target_id] += 1
            edge_records.append((n, e))

    total_deg = {nid: out_deg.get(nid, 0) + in_deg.get(nid, 0) for nid in by_id}
    top_hubs = sorted(total_deg.items(), key=lambda x: -x[1])[:20]

    by_type = Counter(n.node_type.value for n in nodes)
    lang_summary = graph.language_summary or _language_summary_from_nodes(nodes)

    # Cross-file, high-confidence CALLS/IMPORTS (readable signal)
    notable: list[tuple[float, str]] = []
    for src, e in edge_records:
        tgt = by_id.get(e.target_id)
        if tgt is None:
            continue
        if src.file_path == tgt.file_path:
            continue
        if e.confidence < 0.5:
            continue
        if e.edge_type.value not in ("CALLS", "IMPORTS", "INHERITS"):
            continue
        line = (
            f"- `{src.name}` (`{os.path.basename(src.file_path)}`) "
            f"→ `{tgt.name}` (`{os.path.basename(tgt.file_path)}`) "
            f"— **{e.edge_type.value}** conf={e.confidence:.2f} ({edge_provenance(e.confidence)})"
        )
        notable.append((e.confidence, line))
    notable.sort(key=lambda x: -x[0])
    notable_lines = [x[1] for x in notable[:15]]

    unresolved = sum(1 for _, e in edge_records if not e.resolved)
    total_e = len(edge_records)
    unresolved_ratio = (unresolved / total_e) if total_e else 0.0

    lines: list[str] = [
        f"# CodeGraph report: `{graph.repo}`",
        "",
        "Auto-generated summary of the stored code graph (deterministic, no LLM).",
        "",
        "## Overview",
        "",
        f"- **Nodes:** {len(nodes)}",
        f"- **Edges:** {total_e}",
        f"- **Unresolved edge ratio:** {unresolved_ratio:.2%}",
        f"- **Git hash:** `{graph.git_hash or 'n/a'}`",
        f"- **Repo root:** `{graph.repo_root or 'n/a'}`",
        "",
        "## Nodes by type",
        "",
    ]
    for t, cnt in sorted(by_type.items(), key=lambda x: -x[1]):
        lines.append(f"- **{t}:** {cnt}")
    lines.extend(["", "## Nodes by language", ""])
    for lang, cnt in lang_summary.items():
        lines.append(f"- **{lang}:** {cnt}")
    lines.extend(["", "## Hub symbols (by total degree)", ""])
    for nid, deg in top_hubs:
        n = by_id.get(nid)
        if not n:
            continue
        short = os.path.basename(n.file_path) if n.file_path else "?"
        lines.append(
            f"- **{n.name}** (`{n.node_type.value}`, `{short}:{n.line_start}`) — degree **{deg}**"
        )
    lines.extend(["", "## Notable cross-file edges (sample)", ""])
    if notable_lines:
        lines.extend(notable_lines)
    else:
        lines.append("_No cross-file CALLS/IMPORTS/INHERITS edges above 0.5 confidence, or graph is single-file heavy._")
    lines.extend(
        [
            "",
            "## Suggested MCP queries",
            "",
            f"Replace `NODE_ID` with an id from `codegraph query {graph.repo} <SymbolName>` or from JSON export.",
            "",
            "```text",
            f'search_nodes(repo="{graph.repo}", node_type="CLASS", name_pattern="*")',
            "get_neighbors(node_id=NODE_ID, edge_types=[\"CALLED_BY\"], min_confidence=0.5)",
            "get_call_chain(node_id=NODE_ID, direction=\"downstream\", max_depth=3, min_confidence=0.5)",
            "```",
            "",
            "---",
            "",
            "_Generated by CodeGraph `graph_report` export._",
            "",
        ]
    )
    return "\n".join(lines)


def write_graph_report(graph: CodeGraph, output_path: str) -> None:
    text = generate_graph_report_markdown(graph)
    parent = os.path.dirname(os.path.abspath(output_path))
    if parent:
        os.makedirs(parent, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(text)
